### PR TITLE
Fix listings tests@main

### PR DESCRIPTION
**Pull request by BFalquet**
Update snapshots following dependencies update.

Please check if this still fits you

thank you for the review

### CODE REVIEW

**Comment by BFalquet** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by shajoezhu — APPROVED** [review]
thanks @BFalquet , approve to unblock the merge

**Review by shajoezhu — CHANGES_REQUESTED** [review]
hi @BFalquet , snapshot needs update

**Comment by BFalquet** [comment]
@shajoezhu I don't really get it, that is the snapshot i updated. Tests are passing on our server.

**Comment by shajoezhu** [comment]
> @shajoezhu I don't really get it, that is the snapshot i updated. Tests are passing on our server.

can you try up version a few things

formatters >= 0.5.9.9007
rlistings >= 0.2.9.9010

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @BFalquet

**Pull request merged**
