### PR TITLE
[skip vbump] CRAN release 0.2.7

### PR DESCRIPTION
**Pull request by BFalquet**
[skip vbump] https://github.com/insightsengineering/chevron/issues/781

- update NEWS
- update DESCRIPTION and bump dependencies versions

thank you for the review

### CODE REVIEW

**Comment by clarkliming** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by clarkliming** [comment]
the timezone related are updated because of 

> format_date("%d%b%Y")(as.Date("2021-01-01"))
[1] "01JAN2021"
> format_date("%d%b%Y")(as.POSIXct("2021-01-01 00:00:01", tz = "NZ"))
Error in C_force_tz(to_posixct(time), tz, roll_dst) : 
  CCTZ: Unrecognized timezone of the input vector: "NZ"
Calls: <Anonymous> ... <Anonymous> -> .force_tz -> from_posixct -> C_force_tz

only apply the example when tz exists

**Comment by BFalquet** [comment]
> only apply the example when tz exists

That is a very interesting error, in the future we can use the tag `#' @examplesif` https://roxygen2.r-lib.org/articles/rd.html#examples

**Comment by clarkliming** [comment]
> > only apply the example when tz exists
> 
> That is a very interesting error, in the future we can use the tag `#' @examplesIf` https://roxygen2.r-lib.org/articles/rd.html#examples

looks nice!

The tz is system specific so we can't gurantee that this works, so best to use examplesif here to avoid issues  (can we have multiple examplesif section?)

**Comment by clarkliming** [comment]
Rejected because of the check times

Flavor: r-devel-windows-x86_64
Check: Overall checktime, Result: NOTE
  Overall checktime 13 min > 10 min

**Comment by clarkliming** [comment]
now everything is fine and on its way to cran. cheers!

**Review by clarkliming — APPROVED** [review]

**Pull request merged**
