### PR TITLE
Update LBT14 snapshots

### PR DESCRIPTION
**Pull request by edelarua**
LBT14 snapshot updates following https://github.com/insightsengineering/tern/pull/1326

### CODE REVIEW

**Comment by edelarua** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by clarkliming — COMMENTED** [review]
I think the current version is corret, using `n` as denominator. But I would like also include @tianfang1121 to have a look

**Review by BFalquet — COMMENTED** [review]
Please update tern version requirement in DESCRIPTION

**Comment by tianfang1121** [comment]
> I think the current version is corret, using `n` as denominator. But I would like also include @tianfang1121 to have a look

The way the percentage is calculated right now matches with the analysis specification in GDSR LBT14 template

**Review by clarkliming — APPROVED** [review]
thank you, looks good

**Pull request merged**
