### PR TITLE
Bumps `{rmarkdown}` minimal version

### PR DESCRIPTION
**Pull request by averissimo**
# Pull Request

Part of https://github.com/insightsengineering/coredev-tasks/issues/546

Necessary bump to overcome a lack of binary on ppm snapshots that causes an error on minimum strategies for `scheduled` workflows.

### CODE REVIEW

**Comment by averissimo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by clarkliming — APPROVED** [review]
thank you

**Comment by pawelru** [comment]
I have triggered the run to see if it really helps. It's currently in progress here: https://github.com/insightsengineering/chevron/actions/runs/9209294160

**Comment by pawelru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pawelru** [comment]
Hey @clarkliming @BFalquet I would like to bring this to your attention.

Let's analyse the latest run: https://github.com/insightsengineering/chevron/actions/runs/9209294160

There are two issues:
- binary installation - I honestly don't know what's going on so let's skip this for now
- min_isolated - test failures https://github.com/insightsengineering/chevron/actions/runs/9209294160/job/25357827888
```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-assertions.R:69:3'): assert_valid_var.POSIXct works as expected ──
  `assert_valid_var(x)` did not throw the expected error.
  
  [ FAIL 1 | WARN 0 | SKIP 173 | PASS 305 ]
  Error: Test failures
  Execution halted
```
That means that using the minimal dep version as per DESC file (you can find details in the log) we can install dependent packages that would allow `chevron` to be installed (i.e. the conditions of minimal version are met) but it's failing the test. Please have a look at this and I guess you can commit to that branch. Thank you!

**Comment by averissimo** [comment]
> min_isolated - test failures

This was solved with bumping lubridate up

**Pull request merged**
